### ISSUE TITLE
Wrong commonjs types

### ISSUE THREAD

**Issue by TimTechDev** [Bigfish8/esbuild-plugin-vue-next#3]
Hi,
I just noticed that the types for a commonjs require import are wrong:

```js
const pluginVue = require("esbuild-plugin-vue-next");

/** @type {import('esbuild').BuildOptions} */
const BuildOptions = {
    plugins: [pluginVue()], // will cause a type error (ts2349: This expression is not callable.)
    // is defined at runtime.
}

```

```js
const pluginVue = require("esbuild-plugin-vue-next").default;

/** @type {import('esbuild').BuildOptions} */
const BuildOptions = {
    plugins: [pluginVue()], // correct type but will fail at runtime
    // (with "TypeError: This expression is not callable.")
}
```
esModuleInterop is set to true.

[TS Handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports)

**Comment by Bigfish8** [comment]
I dont reproduce the problem.Could you please provide a reproduction repository?

**Comment by TimTechDev** [comment]
https://github.com/Tim-Tech-Dev/esbuild-plugin-vue-next-issue-1

**Comment by Bigfish8** [comment]
Sorry for be late.
It seems difficult to be compatible with type check for js file.If you want check type in js file, you can use `import pluginVue from 'esbuild-plugin-vue-next'` instead of `const pluginVue = require("esbuild-plugin-vue-next")` and add `"type": "module"` in your `package.json`.
